// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ProjectDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Aggregate creation timestamp (UTC).",
				MarkdownDescription: "Aggregate creation timestamp (UTC).",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional free-form description. Empty string when the\noperator did not set one (the wire shape never carries\n`null` for this field).\n",
				MarkdownDescription: "Optional free-form description. Empty string when the\noperator did not set one (the wire shape never carries\n`null` for this field).\n",
			},
			"domain_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Parent Domain identifier (UUIDv7).",
				MarkdownDescription: "Parent Domain identifier (UUIDv7).",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Project identifier (UUIDv7). Bound on `/v1/projects/{id}` for\nthe tenancy CRUD surface and on\n`/v1/projects/{id}/credentials` for the operator-facing\nOpenBao Credential Broker inventory list.\n",
				MarkdownDescription: "Project identifier (UUIDv7). Bound on `/v1/projects/{id}` for\nthe tenancy CRUD surface and on\n`/v1/projects/{id}/credentials` for the operator-facing\nOpenBao Credential Broker inventory list.\n",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Human-readable Project name (trimmed at the aggregate).",
				MarkdownDescription: "Human-readable Project name (trimmed at the aggregate).",
			},
			"slug": schema.StringAttribute{
				Computed:            true,
				Description:         "Kebab-case URL handle. Stable for the lifetime of the\nProject — see the `tenancy` tag description for the\nimmutability rationale.\n",
				MarkdownDescription: "Kebab-case URL handle. Stable for the lifetime of the\nProject — see the `tenancy` tag description for the\nimmutability rationale.\n",
			},
			"sub_range_cidr": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional canonical RFC 4632 sub-range reservation inside\nthe parent Domain's mesh_cidr. Cross-Project non-overlap\nwithin the parent Domain is enforced by the SQL GIST\nexclusion constraint on\n`plexsphere.project_mesh_ip_reservations`.\n",
				MarkdownDescription: "Optional canonical RFC 4632 sub-range reservation inside\nthe parent Domain's mesh_cidr. Cross-Project non-overlap\nwithin the parent Domain is enforced by the SQL GIST\nexclusion constraint on\n`plexsphere.project_mesh_ip_reservations`.\n",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Last-modified timestamp (UTC). Bumped by every mutator —\n`Rename`, `ChangeDescription`, `ReserveSubRange`,\n`ResizeSubRange`, `ReleaseSubRange`.\n",
				MarkdownDescription: "Last-modified timestamp (UTC). Bumped by every mutator —\n`Rename`, `ChangeDescription`, `ReserveSubRange`,\n`ResizeSubRange`, `ReleaseSubRange`.\n",
			},
		},
	}
}

type ProjectModel struct {
	CreatedAt    types.String `tfsdk:"created_at"`
	Description  types.String `tfsdk:"description"`
	DomainId     types.String `tfsdk:"domain_id"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Slug         types.String `tfsdk:"slug"`
	SubRangeCidr types.String `tfsdk:"sub_range_cidr"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}
