// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ProjectResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Aggregate creation timestamp (UTC).",
				MarkdownDescription: "Aggregate creation timestamp (UTC).",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional free-form description. Whitespace-only strings\nare rejected by the aggregate (the operator most likely\nfat-fingered the field instead of meaning to clear it).\n",
				MarkdownDescription: "Optional free-form description. Whitespace-only strings\nare rejected by the aggregate (the operator most likely\nfat-fingered the field instead of meaning to clear it).\n",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(1024),
				},
			},
			"domain_id": schema.StringAttribute{
				Required:            true,
				Description:         "Parent Domain identifier (UUIDv7). The handler authorises\n`manage` on `domain:<id>` BEFORE invoking the service\n.\n",
				MarkdownDescription: "Parent Domain identifier (UUIDv7). The handler authorises\n`manage` on `domain:<id>` BEFORE invoking the service\n.\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Project identifier (UUIDv7).",
				MarkdownDescription: "Project identifier (UUIDv7).",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Human-readable Project name. Whitespace-only is rejected.",
				MarkdownDescription: "Human-readable Project name. Whitespace-only is rejected.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"slug": schema.StringAttribute{
				Required:            true,
				Description:         "Kebab-case URL handle. The aggregate's `ParseSlug` enforces\nthe same regex; surfacing the pattern here lets the\ngenerated client validate before the round-trip.\n",
				MarkdownDescription: "Kebab-case URL handle. The aggregate's `ParseSlug` enforces\nthe same regex; surfacing the pattern here lets the\ngenerated client validate before the round-trip.\n",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 64),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(-[a-z0-9]+)*$"), ""),
				},
			},
			"sub_range_cidr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional canonical RFC 4632 sub-range reservation. Must\nbe contained in the parent Domain's mesh_cidr and must\nnot overlap a sibling Project's reservation. Surfaces as\n`409 sub_range_overlap` on conflict.\n",
				MarkdownDescription: "Optional canonical RFC 4632 sub-range reservation. Must\nbe contained in the parent Domain's mesh_cidr and must\nnot overlap a sibling Project's reservation. Surfaces as\n`409 sub_range_overlap` on conflict.\n",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Last-modified timestamp (UTC). Bumped by every mutator —\n`Rename`, `ChangeDescription`, `ReserveSubRange`,\n`ResizeSubRange`, `ReleaseSubRange`.\n",
				MarkdownDescription: "Last-modified timestamp (UTC). Bumped by every mutator —\n`Rename`, `ChangeDescription`, `ReserveSubRange`,\n`ResizeSubRange`, `ReleaseSubRange`.\n",
			},
		},
	}
}

type ProjectModel struct {
	CreatedAt    types.String `tfsdk:"created_at"`
	Description  types.String `tfsdk:"description"`
	DomainId     types.String `tfsdk:"domain_id"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Slug         types.String `tfsdk:"slug"`
	SubRangeCidr types.String `tfsdk:"sub_range_cidr"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}
